// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'about-the-game',
    'why-this-game',
    'narrator',
    {
      type: 'category',
      label: 'Basic mechanics',
      collapsed: true,
      link: { type: "doc", id: "basic-mechanics/index" },
      items: [
        'basic-mechanics/foundation',
        'basic-mechanics/risk',
        'basic-mechanics/d100-roll',
        'basic-mechanics/fumbles',
        'basic-mechanics/crits',
      ]      
    },
    {
      type: 'category',
      label: 'Dungeon exploration',
      collapsed: true,
      link: { type: "doc", id: "dungeon-exploration/index" },
      items: [
        'dungeon-exploration/time',
        'dungeon-exploration/movement',
        'dungeon-exploration/supplies',
        'dungeon-exploration/experience',
        'dungeon-exploration/death',
      ]      
    },
    {
      type: 'category',
      label: 'Settlements',
      collapsed: true,
      link: { type: "doc", id: "settlements/index" },
      items: [
        'settlements/shops',
      ]      
    },
    {
      type: 'category',
      label: 'Combat',
      collapsed: true,
      link: { type: "doc", id: "combat/index" },
      items: [
        'combat/initiative',
        'combat/turns',
        'combat/rounds',
        'combat/zones',
        'combat/actions',
        'combat/damage',
        'combat/conditions',
        'combat/flight',
      ]      
    },
    {
      type: 'category',
      label: 'Characters',
      collapsed: true,
      link: { type: "doc", id: "characters/index" },
      items: [
        'characters/creation',
        {
          type: 'category',
          label: 'Backgrounds',
          collapsed: true,
          link: { type: "doc", id: "characters/backgrounds/index" },
          items: [
            {
              type: 'category',
              label: 'Upgrades',
              collapsed: true,
              link: { type: "doc", id: "characters/backgrounds/upgrades/index" },
              items: [
                'characters/backgrounds/upgrades/enhancement',
                'characters/backgrounds/upgrades/resources',
                'characters/backgrounds/upgrades/momentum',
                'characters/backgrounds/upgrades/audacity',
                'characters/backgrounds/upgrades/reflexes',
                'characters/backgrounds/upgrades/instinct',
                'characters/backgrounds/upgrades/control',
              ]
            },
            'characters/backgrounds/athlete', 
            'characters/backgrounds/charlatan',
            'characters/backgrounds/ranger',
            'characters/backgrounds/sage',
            'characters/backgrounds/tinkerer'
          ],
        },
        {
          type: 'category',
          label: 'Classes',
          collapsed: true,
          link: { type: "doc", id: "characters/classes/index" },
          items: [
            'characters/classes/fighter',
            'characters/classes/barbarian',
            'characters/classes/guardian',
            'characters/classes/rogue',
            'characters/classes/marksman',   
            'characters/classes/elementalist',
            'characters/classes/healer',
          ]
        },
        'characters/vitality',
        'characters/mana',
        'characters/evasion',
        'characters/armor',
        'characters/magic-number',
        'characters/destiny-points',
        'characters/encumbrance',
        'characters/coins',
        'characters/progression',
      ]
    },
    {
      type: 'category',
      label: 'Skills',
      collapsed: true,
      link: { type: "doc", id: "skills/index" },
      items: [
        {
          type: 'category',
          label: 'Characteristics',
          collapsed: true,
          link: { type: "doc", id: "skills/characteristics/index" },
          items: [
            'skills/characteristics/precision',
            'skills/characteristics/mana-cost',
            'skills/characteristics/vitality-cost',
          ]      
        },
        'skills/general',
      ]      
    },
    {
      type: 'category',
      label: 'Objects',
      collapsed: true,
      link: { type: "doc", id: "objects/index" },
      items: [
        'objects/weapons',
        'objects/exploration-gear',
      ]      
    },
    {
      type: 'category',
      label: 'Creatures',
      collapsed: true,
      link: { type: "doc", id: "creatures/index" },
      items: [
        'creatures/a',
      ]      
    },
  ],
};

export default sidebars;
