export const keywordsES = [
  "maná",
  "provisión", "provisiones",
  "tirada d100",
  "trasfondo",
  "primario",
  "secundario",
  "sin experiencia",
  "mejora",
  "reflejo",
  "director de juego",
  "jugador", "jugadores",
  "personaje",
  "riesgo",
  "atleta",
  "charlatán",
  "montaraz",
  "sabio",
  "manitas",
  "clase",
  "trivial",
  "fácil",
  "moderada",
  "difícil",
  "extrema",
  "precisión",
  "evasión física",
  "evasión mágica",
  "evasión",
  "armadura ligera",
  "armadura media",
  "armadura pesada",
  "armadura",
  "número mágico",
  "zona",
  "turno"

];

export const keywordsEN = [
];
